language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python -c "import nltk; nltk.download('averaged_perceptron_tagger')"
# command to run tests
script:
  - python -m pytest
